services:

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      PORT: ${SERVER_PORT}
      DB: ${DB_URL}

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}

    depends_on:
      - server

    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"